### ISSUE TITLE
Source code links 404 in CT

### ISSUE THREAD

**Issue by civing** [whitesadd/erlangBlackJack#1]
Example

Following link from stack trace in:
file:///home/fryking/src/erlangBlackJack/var/logs/ct_run.ct@heimdal.2017-03-22_22.18.49/src.erlangBlackJack.logs/run.2017-03-22_22.18.49/player_suite.tc001_init_stop.html#end

this is the link:
file:///home/fryking/src/erlangBlackJack/var/logs/ct_run.ct@heimdal.2017-03-22_22.18.49/src.erlangBlackJack.logs/run.2017-03-22_22.18.49/player_suite.src.html#104

Gives 404

**Comment by whitesadd** [comment]
Strange... It works with Jenkins

https://jenkins.fryking.se/job/ebj-check/74/artifact/var/logs/ct_run.ct@heimdal.2017-03-22_22.12.22/ebj-check.workspace.logs/run.2017-03-22_22.12.23/player_suite.src.html#104

**Comment by whitesadd** [comment]
I do not have permissions to check your home directory, so I am not able to give a closer look at the problem with your local repo

**Comment by civing** [comment]
True, it's here:
https://jenkins.fryking.se/job/ebj-check/74/artifact/var/logs/ct_run.ct@heimdal.2017-03-22_22.12.22/ebj-check.workspace.logs/run.2017-03-22_22.12.23/player_suite.src.html#104

It's not showing up with when I ran r_tests.sh though ..

Will close this issue.
