### ISSUE TITLE
Link to test results in gerrit

### ISSUE THREAD

**Issue by civing** [whitesadd/erlangBlackJack#2]
Is it possible to post the link to the test result (not only jenkins job) in gerrit comment?

**Comment by whitesadd** [comment]
Sure! Do you want me to do it? Or you want to learn how to do it yourself?

**Comment by civing** [comment]
I won't mind you doing it! ☺️

**Comment by whitesadd** [comment]
Good! Give me 30 min.

**Comment by civing** [comment]
Looks good!
Could we get coverage? :)

**Comment by whitesadd** [comment]
Hmmm... that one is inside the CT logs, so I deem it unnecessary...

**Comment by civing** [comment]
Happy? Should we close?
